on:
  workflow_dispatch:

jobs:
  reusable-matrix-test:
    strategy:
      fail-fast: false
      matrix:
        some: ["true", "false"]
    uses: ./.github/workflows/logic.yml
    with:
        some: ${{ matrix.some }}
  check-deps:
    if: ${{ always() }}
    needs:
      - reusable-matrix-test
    runs-on: ubuntu-latest
    steps:
    - name: Check dependencies
      run: |
        echo "RESULT: $RESULT"
      env:
        RESULT: ${{ needs.reusable-matrix-test.result }}