on:
  workflow_dispatch:
    inputs:
      target-json-arg:
        description: 'JSON array of targets'
        required: true
        default: '["target1", "target2"]'

jobs:
  list-targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}
    steps:
    - name: List targets
      id: list-targets
      run: |
        echo "targets=${TARGET_JSON_ARG}" >> "$GITHUB_OUTPUT"
      env:
        TARGET_JSON_ARG: ${{ github.event.inputs.target-json-arg }}
  reusable-matrix-test:
    if: ${{ needs.list-targets.outputs.targets != '[]' }}
    needs:
      - list-targets
    strategy:
      fail-fast: false
      matrix:
        some: ${{ fromJson(needs.list-targets.outputs.targets) }}
    uses: ./.github/workflows/logic.yml
    with:
        some: ${{ matrix.some }}
  check-deps:
    if: ${{ always() }}
    needs:
      - reusable-matrix-test
    runs-on: ubuntu-latest
    steps:
    - name: Check dependencies
      run: |
        echo "RESULT: $RESULT"
        test "$RESULT" != "failure"
      env:
        RESULT: ${{ needs.reusable-matrix-test.result }}